### ISSUE TITLE
LOTV: Zerg macro doesn't work when queuing injects

### ISSUE THREAD

**Issue by gravelweb** [ggtracker/ggtrackerstack#50]
Looks like queueing injects causes the previous inject to be unregistered.

sc2parse/plugins.py:1153 (ZergMacroTracker)

```
        if target_hatch_id not in owner.hatches:
            target_hatch.injects = [event.frame]
            owner.hatches[target_hatch_id] = target_hatch
        else:
            # If not enough time has passed, the last one didn't happen
            if event.frame - target_hatch.injects[-1] < INJECT_TIME:
                print "Previous inject on {0} at {1} failed".format(target_hatch, target_hatch.injects[-1])
                target_hatch.injects[-1] = event.frame
            else:
                target_hatch.injects.append(event.frame)
```

**Comment by dsjoerg** [comment]
Fixed by https://github.com/ggtracker/sc2reader/pull/14 and https://github.com/dsjoerg/ggpyjobs/pull/11

**Comment by gravelweb** [comment]
The queued injects are still not showing up in the graph, because of the code above ^^ I'm looking to solve this in the beginning of July.
